### ISSUE TITLE
Passing all examples without completing methods

### ISSUE THREAD

**Issue by gooryalhamed** [learn-co-curriculum/scraping-flatiron-code-along#19] opened 2016-11-01 13:46 UTC
I was coding along with the instructions in the lesson, I got all tests passing without writing #make_courses methods.

**Comment by bhollan** [comment] 2017-01-24 22:35
@aturkewi 
Ran into this again.  [Student code](https://github.com/Terry-Thompson/scraping-flatiron-code-along-v-000/blob/master/lib/scraper.rb) (updated when student finishes lab).

**Comment by aturkewi** [comment] 2017-02-10 22:28
Hey @cjbrock just wanted to tag you in on this one.
I don't really know anything about this lab, but it sounds like we may want to either add tests for `#make_courses` _or_ just delete mention of it from the Readme if it's not being use?

**Comment by aaronkelton** [comment] 2017-05-09 19:39
Sorry, just raised another issue same as this one. No resolution yet?

**Comment by curiositypaths** [comment] 2017-11-27 22:07
Hi there,

I'm having difficulty reproducing the issue since #make_courses is tested within the Scraper specs. I'm going to close the issue for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment and a link to your fork, I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by curiositypaths** 2017-11-27 22:07 UTC
Labels: Curriculum
